[package]
name = "zod"
version = "0.1.0"
authors = ["Owen Platt <owen@ojhp.net>"]
edition = "2021"
rust-version = "1.70"
description = "A roguelike game"
readme = "README.md"
repository = "https://github.com/ojhp/zod"
license = "MIT"
keywords = ["game", "roguelike"]
categories = ["games"]
